layout_spectrum: 0.8885373633393631
typography_spectrum: 0.7629844482415494
color:
  brandStrength: 0.8526376414121968
  lightness: 0.19731231532483776
  saturation: 0.9492942182799929
  rhythmicContrast: 0.1055907079857765
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Pack860HB.org
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b990079-72db-417d-b71c-102af48413b6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b990079-72db-417d-b71c-102af48413b6.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/20022e48-9002-4786-b277-1c0b9c09ada3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/20022e48-9002-4786-b277-1c0b9c09ada3.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Hermosa Beach Pack 860
description: 'Cub Scouts: Prepared for Life'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fe94d09-4c25-4ecb-a687-aa80d769a634.jpg
author:
  name: Son of a Network Studio & Consultancy
  email: rknyman@Sonofa.Net
  url: 'https://Sonofa.Net'
purpose:
  - type: contact
    url: 'mailto:Pack860HB@Gmail.com'
    label: 'For further information:'
  - type: internal
    label: 'Start here:'
    item: 452e9070-f7fd-4bf0-a4a6-6f1210151281
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dae6c449-a83d-4222-9055-a3b48bd3dd81.png
