layout_spectrum: 0.6173255308106136
typography_spectrum: 0.9982128461205981
color:
  brandStrength: 0.8803113950611932
  lightness: 0.2481426810685287
  saturation: 0.9922551907424695
  rhythmicContrast: 0.9210008059308339
  brandColors:
    - '#FFFFFF'
    - '#2F384B'
    - '#2A87B0'
    - '#FFD401'
    - '#BAC9E8'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Pack860HB.org
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/06dbab76-056f-41f5-bb83-3284469962a2.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/06dbab76-056f-41f5-bb83-3284469962a2.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0f52e595-872b-4889-be1f-0ebbfb7cbc64.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0f52e595-872b-4889-be1f-0ebbfb7cbc64.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Hermosa Beach Pack 860
description: 'Cub Scouts: Prepared for Life.'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fe94d09-4c25-4ecb-a687-aa80d769a634.jpg
author:
  name: Son of a Network Studio & Consultancy
  email: rknyman@Sonofa.Net
  url: 'https://Sonofa.Net'
purpose:
  - type: external
    label: Get Started HERE! New Scout Inquiry Form
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLSfsyb7MamLVRMVXkgEhgajQCJDygNzzWWhqPGEhHmbvXYISAg/viewform?usp=sf_link
  - type: contact
    url: 'mailto:Pack860HB@gmail.com'
    label: Have a question? Email us!
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dae6c449-a83d-4222-9055-a3b48bd3dd81.png
