colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Pack860HB
layout_spectrum: 0.2627110332250595
typography_spectrum: 0.9299557730555534
color:
  brandStrength: 0.014863267308101058
  lightness: 0.21879683854058385
  saturation: 0.891944560687989
  rhythmicContrast: 0.6889065678697079
  brandColors:
    - '#2E3649'
    - '#2A87B0'
    - '#2D6281'
    - '#37BEF5'
    - '#2C4B62'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/835efdd1-afe2-4f18-8fa0-2fdce6fb0e01.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/835efdd1-afe2-4f18-8fa0-2fdce6fb0e01.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f57278d-c072-4377-98a9-f40941d8edb2.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6f57278d-c072-4377-98a9-f40941d8edb2.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Hermosa Beach Pack 860
description: 'Cub Scouts: Prepared for Life'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fe94d09-4c25-4ecb-a687-aa80d769a634.jpg
author:
  name: Son of a Network Studio & Consultancy
  email: rknyman@Sonofa.Net
  url: 'https://Sonofa.Net'
purpose:
  - type: contact
    url: 'mailto:Pack860HB@Gmail.com'
    label: 'For further information:'
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dae6c449-a83d-4222-9055-a3b48bd3dd81.png
